version: '3.8'

services:
  nginx:
    image: nginx:mainline-alpine3.18-slim
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config:/etc/nginx/conf.d/

  php:
    build:
      context: ./docker-wp/php
    ports:
      - "9000:9000"
