x-env: &env
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress
  MYSQL_DATABASE: wordpress
  MYSQL_HOST: db
  MYSQL_ROOT_PASSWORD: root

services:
  nginx:
    image: nginx:alpine3.18-slim
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config:/etc/nginx/conf.d/
      - ./wordpress:/var/www/html/wordpress

  wp:
    image: wordpress:php8.2-fpm-alpine
    depends_on:
      - db
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      <<: *env
    volumes:
      - ./wordpress:/var/www/html/wordpress

  db:
    image: mariadb:10.8
    restart: always
    environment:
      <<: *env
    volumes:
      - /var/lib/mysql

  wp_cli:
    image: wordpress:cli-php8.2
    depends_on:
      - wp
      - db
    environment:
      <<: *env
    user: 1000:1000
    working_dir: /var/www/html/wordpress
    volumes:
      - ./wordpress:/var/www/html/wordpress

  composer:
    image: composer:2.6.5
    working_dir: /var/www/html/
    user: 1000:1000
    depends_on:
      - wp
    volumes:
      - ./wordpress:/var/www/html/wordpress
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    command: ["composer", "install", "--prefer-dist", "--optimize-autoloader"]

