services:
  nginx:
    image: nginx:alpine3.18-slim
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8888:8888"
    links:
      - php
      - db
      - pma
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config:/etc/nginx/conf.d/
      - ./wordpress:/var/www/wordpress

  php:
    build:
      context: php
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/wordpress

  db:
    image: alpinelinux/mariadb
    restart: always
    environment:
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_HOST: db
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql

  pma:
    image: phpmyadmin:5.2.1-fpm-alpine
    restart: unless-stopped
    links:
      - db
    ports:
      - 8080:8080
    environment:
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - phpmyadmin:/var/www/html

volumes:
  phpmyadmin:
