services:
  nginx:
    image: nginx:alpine3.18-slim
    restart: unless-stopped
    ports:
      - "8989:80"
    links:
      - php
      - db
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config:/etc/nginx/conf.d/
      - ./wordpress:/var/www/wordpress

  php:
    build:
      context: php
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/wordpress

  db:
    image: alpinelinux/mariadb
    restart: always
    environment:
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_HOST: db
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql
