FROM php:8.2-fpm-alpine

RUN apk update && \
    apk --no-cache add \
    php82-bcmath \
    php82-exif \
    php82-iconv \
    php82-intl \
    php82-opcache \
    php82-pecl-igbinary \
    php82-pecl-imagick \
    php82-shmop \
    php82-zip

